#!/bin/bash

set -x

BUILD=build
OPT='-g -Werror'

## Create the build directory
mkdir -p $BUILD 
## Copy files to build
ln -s -f ../ll.c   $BUILD/ll.c
ln -s -f ../ll.h   $BUILD/ll.h
ln -s -f ../main.c $BUILD/main.c

## Build individual files
python scripts/mkh.py ll.c > $BUILD/ll_proto.h
gcc $OPT $BUILD/ll.c -c -o $BUILD/ll.o

python scripts/mkh.py main.c > $BUILD/main_proto.h
gcc $OPT $BUILD/main.c -c -o $BUILD/main.o

## Link objects to exec
gcc $OPT $BUILD/ll.o $BUILD/main.o -o $BUILD/exec

## Soft link exec
ln -s -f $BUILD/exec exec
echo "BUILD complete!!"
